### ISSUE TITLE
Feature request: extend the library to support 01/02/04/08/16 parts

### ISSUE THREAD

**Issue by fijam** [adafruit/Adafruit_CircuitPython_24LC32#15] opened 2022-02-11 13:57 UTC
It would be great if this library could also support smaller eeprom chips.

The main difference for those is in addressing, 04 parts borrow one bit from the slave address for the memory address (9 bits to address 500 bytes), 08 parts borrow 2 and 16 parts borrow three.

![image](https://user-images.githubusercontent.com/75824/153603999-4d50e0fd-81b0-4956-b8e2-b0ffb8c0565b.png)

Following the slave address, only one byte is used for the rest of the address.

![image](https://user-images.githubusercontent.com/75824/153604184-7e9b8029-cf1c-4a7b-ad64-7122a6cc0b08.png)

**Comment by tekktrik** [comment] 2022-10-06 20:51
This is a duplicate of #8.  The decision was made to keep driver libraries focused on their target.  For EEPROMs, it makes more sense to create a library.  The linked pull issue links to a guide showing how to make a library for the Community Bundle, if you would like to make a more generalized (or other smaller) libraries.

**Closed as completed by tekktrik** 2022-10-06 20:51 UTC
